name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 9 * * *'
  repository_dispatch:
    types: [ build ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Build documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 scripts/build.py _site
        chmod -v -R +rX "_site/"

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4

  deploy:

    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
